title: Coding Challenges
html_title: >-
  <span class="blue">Coding</span><span class="red">Challenges</span>&nbsp;
year: 2021
email: brg@brgurukul.org
description: >- # this means to ignore newlines until "baseurl:"
  Coding challenges related to programming, frameworks and others
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://codingchallenges.org" # the base hostname & protocol for your site, e.g. http://example.com
image_base_url: /assets/img
author: BRG
author_url: https://freelancerbrg.com
repo: https://github.com/brgurukul/codingchallenges.org
solution_repo: https://github.com/brgurukul/solutions.codingchallenges.org/

twitter_username: coolbrg
github_username:  coolbrg

google_analytics: # your google analytics id

permalink: /:title

collections:
  html-css-js:
    output: true
    permalink: /html-css-js/:title

contacts:
  facebook:
    url: https://www.facebook.com/brgurukul
    label: Facebook
    class: bx bxl-facebook
  twitter:
    url: https://twitter.com/coolbrg/
    label: Twitter
    class: bx bxl-twitter
    username: "@coolbrg"
  github:
    url: https://github.com/brgurukul/
    label: GitHub
    class: bx bxl-github
  linkedin:
    url: https://www.linkedin.com/company/brgurukul
    label: LinkdIn
    class: bx bxl-linkedin
  email:
    url: mailto:brg@brgurukul.org
    label: Email
    class: bx bx-mail-send
  # youtube:
  #   url: https://www.youtube.com/channel/UC8p8tlnY5fykNYv2vZHvQDg
  #   label: YouTube Channel
  #   class: bx bxl-youtube

# Build settings
markdown: kramdown
